version: "3.9"

networks:
  front:
    external: false

services:
  front:
    build: .
    image: front
    command: yarn start
    container_name: front
    ports:
      - "3000:3000"

    networks:
      - front