services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    image: front
    container_name: front
    ports:
      # - "127.0.0.1:8080:3000" 
      - "3000:3000"
      # 1-прод, 2-песочница 