services:
  front:
    build: 
      context: .
      dockerfile: Dockerfile
    image: front
    container_name: front
    ports:
      - "127.0.0.1:8080:3000" 
      # - "3000:3000"
      # 1-прод, 2-песочница 
    environment:
      - VITE_RUN_MODE=PRODUCTION
      - VITE_DEV_API_URL=http://sandbox.coursehb.ru
      - VITE_PROD_API_URL=https://apidev.coursehb.ru
      - VITE_DEV_IP=http://91.211.248.84:8000
      - VITE_PROD_IP=http://45.88.76.53:8000  