export const arrowUsers = [
  {
    avatar: '',
    name: 'user1',
    email: 'user1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '02.08.2022',
    status: ' на доработке',
    ball: 3,
  },
  {
    avatar: '',
    name: 'user2',
    email: 'aser1@example.com',
    task: ' Проверочная',
    course: 'The Way Java',
    date: '01.08.2022',
    status: 'Отклонено',
    ball: 4,
  },
  {
    avatar: '',
    name: 'user3',
    email: 'rser1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '20.07.2022',
    status: 'Принято',
    ball: 5,
  },
  {
    avatar: '',
    name: 'user4',
    email: 'qer1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '22.07.2022',
    status: 'на доработке',
    ball: 2,
  },
  {
    avatar: '',
    name: 'user5',
    email: 'cuser1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '02.08.2022',
    status: ' на доработке',
    ball: 4,
  },
  {
    avatar: '',
    name: 'user6',
    email: 'ruser1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '02.08.2022',
    status: ' на доработке',
    ball: 3,
  },
  {
    avatar: '',
    name: 'user7',
    email: 'yuser1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '02.08.2022',
    status: ' на доработке',
    ball: 5,
  },
  {
    avatar: '',
    name: 'user8',
    email: 'ouser1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '02.08.2022',
    status: ' на доработке',
    ball: 1,
  },
  {
    avatar: '',
    name: 'user9',
    email: 'user1@example.com',
    task: ' домашнее задание',
    course: 'The Way Java',
    date: '19.06.2022',
    status: ' на доработке',
    ball: 3,
  },
]
