export { authReduce } from './users/slice'
export { courseReduce } from './course/slice'
export { coursesReduce } from './courses/slice'
export { modalReduce } from './modal/slice'
export { platformReduce } from './platform/slice'
