export const studentsTableInfo = {
  students_table_info_id: 1,
  students_table_info: [
    {
      id: 1,
      name: 'Имя',
      order: 1,
      checked: true,
      label: 'student_name',
    },
    {
      id: 2,
      name: 'Email',
      order: 2,
      checked: true,
      label: 'email',
    },
    {
      id: 3,
      name: 'Суммарный балл',
      order: 3,
      checked: false,
      label: 'mark_sum',
    },
    {
      id: 4,
      name: 'Курс',
      order: 4,
      checked: false,
      label: 'course',
    },
    {
      id: 5,
      name: 'Последняя активность',
      order: 5,
      checked: false,
      label: 'last_active',
    },
    {
      id: 6,
      name: 'Прогресс',
      order: 6,
      checked: false,
      label: 'progress',
    },
    {
      id: 10,
      name: 'Дата обновления',
      order: 10,
      checked: true,
      label: 'update_date',
    },
    {
      id: 11,
      name: 'Дата заверения',
      order: 11,
      checked: true,
      label: 'ending_date',
    },
    {
      id: 9,
      name: 'Средний балл',
      order: 9,
      checked: true,
      label: 'average_mark',
    },
    {
      id: 8,
      name: 'Группа',
      order: 8,
      checked: true,
      label: 'group',
    },
    {
      id: 7,
      name: 'Комментарий',
      order: 7,
      checked: false,
      label: 'comments',
    },
  ],
  admin: 1,
}
